{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.mani_auth",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 13726431,
          "sha512": "1d95aa0888320e45d55486754a61e0fbec8f774566a0c3506bbab912d82c7b9dadf444f4e9012e213a9c175dc4ac1b746132517921596dbcdada5e4d01a3596d",
          "sha256": "3baf5af25b0ecaffc1f5b2aaed36a30a8a7d029c595842b71c19db0da120fd39",
          "sha1": "6b3631203a06044cc943791eede2785ed0f8e212",
          "md5": "632bb6010bb63ddc9847c21bc6fd796d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 13726431,
          "sha512": "1d95aa0888320e45d55486754a61e0fbec8f774566a0c3506bbab912d82c7b9dadf444f4e9012e213a9c175dc4ac1b746132517921596dbcdada5e4d01a3596d",
          "sha256": "3baf5af25b0ecaffc1f5b2aaed36a30a8a7d029c595842b71c19db0da120fd39",
          "sha1": "6b3631203a06044cc943791eede2785ed0f8e212",
          "md5": "632bb6010bb63ddc9847c21bc6fd796d"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1100,
          "sha512": "9d00d4850433a01f6549797b4c4ea845e276dabf9a6fa6fa16aa8820eea2788dc2a3a2379098c0cdf686b75c4b95a3e868422fda1fe2864c93e06971c497246c",
          "sha256": "bbc9cbe1c13a3a499a0b991801a0e5ff32bf7a2bdd5b4cdb1690b22557fe7cca",
          "sha1": "e7ab021f2f0ed0324459e604a14227b3633a1c5e",
          "md5": "ce6c48e280197d4dbd2e5de32a1bc2b9"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
