{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "myid_release-1.0.aar",
          "url": "myid_release-1.0.aar",
          "size": 17504,
          "sha512": "c69437c18481bcb1bcf46a7b3318f28af7c9ed17cd8d495a1af879412bf3f319761b6194ea415354537857a7c6768d23e10c23626fdb83f0b532bb002c1de198",
          "sha256": "f83c2132ae2f74fb7f4add5de82cf9cd51e195c9326bb4a6c490c48ca6ed9712",
          "sha1": "b1905a617d5ace0b3a93a528c6180e6eb152df5a",
          "md5": "6c832bd1df166877fd480373fa9078da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk",
          "version": {
            "requires": "2.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "myid_release-1.0.aar",
          "url": "myid_release-1.0.aar",
          "size": 17504,
          "sha512": "c69437c18481bcb1bcf46a7b3318f28af7c9ed17cd8d495a1af879412bf3f319761b6194ea415354537857a7c6768d23e10c23626fdb83f0b532bb002c1de198",
          "sha256": "f83c2132ae2f74fb7f4add5de82cf9cd51e195c9326bb4a6c490c48ca6ed9712",
          "sha1": "b1905a617d5ace0b3a93a528c6180e6eb152df5a",
          "md5": "6c832bd1df166877fd480373fa9078da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_release-1.0-sources.jar",
          "url": "myid_release-1.0-sources.jar",
          "size": 5128,
          "sha512": "04e4f3cb6b2677aa90088ea068d01b41ad0b977dbcec428011e9b16390438ec3168e2dcf749a9d52745e5e7a80856be7c16a1e8e6ebc55b9b0b5eb83a28158ac",
          "sha256": "5367c80faa3cb44533655d32627f62590beb3f7588216737be18b930d369e121",
          "sha1": "ecb3a7f7d92bda147754f35a38c140fbf4a9877a",
          "md5": "92c68f780ff33089eedb439f718c0482"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_release-1.0-javadoc.jar",
          "url": "myid_release-1.0-javadoc.jar",
          "size": 277147,
          "sha512": "2c6dba2869bfbacec20a47555ef06d8322a7481b86312be75a4ff9461a151a3ccd66767e6ab42be479d5dc6b0d4b89a09443f9f27d9671ec8f1f8ee81b57ed3c",
          "sha256": "484316d0976d0956ec9685c5fa3fbb940214c306e7971381a4c85addfa2dddb4",
          "sha1": "876b6a92fe4b35e27b41d8646aed05191f1f21de",
          "md5": "d2cf2d5494e263d9bde784f2dea9484a"
        }
      ]
    }
  ]
}
