{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_profile-1.0.aar",
          "url": "myid_profile-1.0.aar",
          "size": 16351,
          "sha512": "9bc3cd03da8ec1b9042176aed875a34ace24fa34bc94d8a4aa64bd47349863c1d5d216313024cbf801e990ec3abc7a6e7893cd82b043235e68963133ca5698f5",
          "sha256": "edfe8ee02dba2ff2d9e2229db7cf8e07584de1c9f77d0b201bef16ae34cc25f1",
          "sha1": "cd0e50d1182b36b46b17553749a9e977af49d254",
          "md5": "5d5e7a661aa9de1efc7a5f911eef9767"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_profile-1.0.aar",
          "url": "myid_profile-1.0.aar",
          "size": 16351,
          "sha512": "9bc3cd03da8ec1b9042176aed875a34ace24fa34bc94d8a4aa64bd47349863c1d5d216313024cbf801e990ec3abc7a6e7893cd82b043235e68963133ca5698f5",
          "sha256": "edfe8ee02dba2ff2d9e2229db7cf8e07584de1c9f77d0b201bef16ae34cc25f1",
          "sha1": "cd0e50d1182b36b46b17553749a9e977af49d254",
          "md5": "5d5e7a661aa9de1efc7a5f911eef9767"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_profile-1.0-sources.jar",
          "url": "myid_profile-1.0-sources.jar",
          "size": 4922,
          "sha512": "f18705ed4ae1fc7d3fa8e00adc5af3f26a5898398d6d34f4f2a9529a7681fb73c9b7284acd5de6e762c92bb067dfca773007b1157ee469dcc7114e153b5fb962",
          "sha256": "8a56adebd97250d35477b33b5e82c794faabfdc04873c74efc38e7bbeb8439a7",
          "sha1": "dbf89de8c1915656051966ded3515dc54bf00ad6",
          "md5": "f07251c88ac7eb1b0c25cfa032990e81"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_profile-1.0-javadoc.jar",
          "url": "myid_profile-1.0-javadoc.jar",
          "size": 277147,
          "sha512": "2c6dba2869bfbacec20a47555ef06d8322a7481b86312be75a4ff9461a151a3ccd66767e6ab42be479d5dc6b0d4b89a09443f9f27d9671ec8f1f8ee81b57ed3c",
          "sha256": "484316d0976d0956ec9685c5fa3fbb940214c306e7971381a4c85addfa2dddb4",
          "sha1": "876b6a92fe4b35e27b41d8646aed05191f1f21de",
          "md5": "d2cf2d5494e263d9bde784f2dea9484a"
        }
      ]
    }
  ]
}
