{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.mani_auth",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 13294251,
          "sha512": "2c60296334e727598e6a3e9a54e1713f90496e08475822371e7acadcebacd601abfe97d56ddba803678f6650367e1ba8129b2dd9bb76273d378078dbf2871ace",
          "sha256": "724d4a7604a2b1acf886362341264abef22ff8b219fa9b66f75220ee50c0567b",
          "sha1": "7a9e0b34115a2f12def5330e409c12683372f18b",
          "md5": "e809f05490e86c9e52b891646a30ecd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 13294251,
          "sha512": "2c60296334e727598e6a3e9a54e1713f90496e08475822371e7acadcebacd601abfe97d56ddba803678f6650367e1ba8129b2dd9bb76273d378078dbf2871ace",
          "sha256": "724d4a7604a2b1acf886362341264abef22ff8b219fa9b66f75220ee50c0567b",
          "sha1": "7a9e0b34115a2f12def5330e409c12683372f18b",
          "md5": "e809f05490e86c9e52b891646a30ecd8"
        }
      ]
    }
  ]
}
