{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.mani_auth",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 13124605,
          "sha512": "0c39e4205cd5f484381748f2d38eab9fd81d33a4d16a42288abedb0d1428d89d6a578fb6097ca19a81c237ceb24a578d99b4a65d0623a2c1e2a789bdc914a34b",
          "sha256": "c2bbf61e3a2a4d3bb0f999046f38427699654ad0edc16706d1b2eae79184ed24",
          "sha1": "ab1e33e808e9101ba5f3a4670c03ac08f12141e0",
          "md5": "9410a54e27c8f9a2605ed260ffda3d76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 13124605,
          "sha512": "0c39e4205cd5f484381748f2d38eab9fd81d33a4d16a42288abedb0d1428d89d6a578fb6097ca19a81c237ceb24a578d99b4a65d0623a2c1e2a789bdc914a34b",
          "sha256": "c2bbf61e3a2a4d3bb0f999046f38427699654ad0edc16706d1b2eae79184ed24",
          "sha1": "ab1e33e808e9101ba5f3a4670c03ac08f12141e0",
          "md5": "9410a54e27c8f9a2605ed260ffda3d76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-sources.jar",
          "url": "flutter_release-1.0-sources.jar",
          "size": 1756,
          "sha512": "fd2c88ed27babd58d7d217666e45492cfb59888389df131a4261fb66d19d96105d069724b0e8ff09929acccceed90492657c19a630545c25d20f6f8b425e2b2b",
          "sha256": "3e627707b99c81c2f9b7f042b107c7355afd2aef2bc76ec72377f1d2825906d8",
          "sha1": "caa071b89eaeb2374a8c7d6b013cc35c4135e465",
          "md5": "ab5926b22d6121802624e9854fb6f4e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-javadoc.jar",
          "url": "flutter_release-1.0-javadoc.jar",
          "size": 269302,
          "sha512": "d12e16ef73d41374d8e530f042cca6f90771abaa21cf579fad10a87d395be3b2006fc463e46930e7969831b74a88e0a7e5c67cb89bf4691a5b50bfb18b1485ca",
          "sha256": "5397106a1c5dcaedc308e15cc0a9f1be8d9af57d6dc6e5d89bd230a99c193760",
          "sha1": "370874095df99f8813c9a12b916a036af51fd0c9",
          "md5": "4cdd291cf61f790ddd1d70ddbe8d2f10"
        }
      ]
    }
  ]
}
