{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 16952,
          "sha512": "9be8a1593838be340c57cab1d4dbd0435b82c1ab29c10b2e7b0038a41cf4fc5daa29b97d81efda84848ccc9df6eada1370305c9d9e05d040d401928bd0713657",
          "sha256": "e2eef5c84cca156f04dab618721f986dde65a46cefc41707967b7866dcfe737c",
          "sha1": "79fe95823120191cab717d7b3d44549266be52d3",
          "md5": "d081c69a7dd4a671d0ec22f35de33634"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 16952,
          "sha512": "9be8a1593838be340c57cab1d4dbd0435b82c1ab29c10b2e7b0038a41cf4fc5daa29b97d81efda84848ccc9df6eada1370305c9d9e05d040d401928bd0713657",
          "sha256": "e2eef5c84cca156f04dab618721f986dde65a46cefc41707967b7866dcfe737c",
          "sha1": "79fe95823120191cab717d7b3d44549266be52d3",
          "md5": "d081c69a7dd4a671d0ec22f35de33634"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-sources.jar",
          "url": "myid_debug-1.0-sources.jar",
          "size": 4896,
          "sha512": "efb4bb172f5e1489f46764e0c7dfabd36cab209c157f4603c5589b6c89f358fa9f5a00ca6657970f205a9bb193fbc1153496d2b705eb4a9de2922a9ab17107aa",
          "sha256": "29833a2cef7dff53f1d25adacfe3b564d6b142b409be7df4476b808a28016811",
          "sha1": "dc5b65043b40612029166150067178e42cf6f932",
          "md5": "f97504f9578f34fda7290a618eeb552e"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-javadoc.jar",
          "url": "myid_debug-1.0-javadoc.jar",
          "size": 277147,
          "sha512": "2c6dba2869bfbacec20a47555ef06d8322a7481b86312be75a4ff9461a151a3ccd66767e6ab42be479d5dc6b0d4b89a09443f9f27d9671ec8f1f8ee81b57ed3c",
          "sha256": "484316d0976d0956ec9685c5fa3fbb940214c306e7971381a4c85addfa2dddb4",
          "sha1": "876b6a92fe4b35e27b41d8646aed05191f1f21de",
          "md5": "d2cf2d5494e263d9bde784f2dea9484a"
        }
      ]
    }
  ]
}
