{
  "formatVersion": "1.1",
  "component": {
    "group": "com.corbado.passkeys_android",
    "module": "passkeys_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "passkeys_android_profile-1.0.aar",
          "url": "passkeys_android_profile-1.0.aar",
          "size": 48894,
          "sha512": "2c7a17b6bdc887f3fdd4551467bfba9dd188974219b89114bfb19cdcfb4084dc2fe8f0eb37396fdf2e201cd86e32040ece599b47b2dd2f7f84f2581c81c7995d",
          "sha256": "6b6ab28822b7595d9f182347c8371b177b130b6a5b8f66bd9557803fdac1eaf6",
          "sha1": "881fb198556ff3577070dca8681b5c217655db34",
          "md5": "96bb4c4cde5f9720f44873666075e94c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-fido",
          "version": {
            "requires": "20.0.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "passkeys_android_profile-1.0.aar",
          "url": "passkeys_android_profile-1.0.aar",
          "size": 48894,
          "sha512": "2c7a17b6bdc887f3fdd4551467bfba9dd188974219b89114bfb19cdcfb4084dc2fe8f0eb37396fdf2e201cd86e32040ece599b47b2dd2f7f84f2581c81c7995d",
          "sha256": "6b6ab28822b7595d9f182347c8371b177b130b6a5b8f66bd9557803fdac1eaf6",
          "sha1": "881fb198556ff3577070dca8681b5c217655db34",
          "md5": "96bb4c4cde5f9720f44873666075e94c"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "passkeys_android_profile-1.0-sources.jar",
          "url": "passkeys_android_profile-1.0-sources.jar",
          "size": 14939,
          "sha512": "1be8dbc7b623dc244afbeedb5b66a07df8ffbbfd773eb44a182397ca94bf302ae01308dc64c503ca12f409fa2f47db23304239033d2837f905d718b98021f568",
          "sha256": "76ec5c93f08da7474a2ff6dc3f3d12a7ae130a9f0b82261d32063c0841a63e4c",
          "sha1": "5e1d6495f1a7a94c83ecd112e58854ea0aa18487",
          "md5": "fa4c33dbf1f4173aa00753897518f415"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "passkeys_android_profile-1.0-javadoc.jar",
          "url": "passkeys_android_profile-1.0-javadoc.jar",
          "size": 403696,
          "sha512": "a3eae398cad1c757b1fe3ed501c8d4de5effad415d35429719cf94f0da527e36dfd7ef33d73bed7a1374845fd1b145f487bad244e4a593094604200138aa45f0",
          "sha256": "6acae883999e1362e72a8f9ca6d1dfb79ecb148e0a9d61ac212051665e831953",
          "sha1": "8abb6ba02bb512b72fcf0f7630180d66b3af25c5",
          "md5": "98e53064a682ed829896fb0c450261a7"
        }
      ]
    }
  ]
}
